version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_USERNAME: sa
      SA_PASSWORD: admin@77
      ACCEPT_EULA: Y
    volumes:
      - ./volumes/db_storage:/var/opt/mssql/data
      - ./volumes/backup:/var/opt/mssql/Backup
